export const projects = [
  {
    title: 'Asistente Virtual para Adultos Mayores',
    titleEn: 'Virtual Assistant for Elderly People',
    description: 'Asistente por voz sobre Raspberry Pi usando Google Cloud IA.',
    descriptionEn: 'Voice assistant on Raspberry Pi using Google Cloud AI.',
    tags: ['Python', 'Raspberry Pi', 'Google Cloud'],
    link: null,
    detail: {
      photo: '/Disposiitvo.png',
      photoAlt: 'Dispositivo Asistente Virtual para Adultos Mayores',
      introduction: 'Asistente virtual basado en inteligencia artificial generativa e internet de las cosas, diseñado para proporcionar apoyo en el hogar. El sistema integra captura de voz, procesamiento de lenguaje natural en la nube, generación de respuestas mediante modelos de lenguaje y control de dispositivos domésticos inteligentes mediante una arquitectura por capas.',
      introductionEn: 'Virtual assistant based on generative artificial intelligence and the Internet of Things, designed to provide home support. The system integrates voice capture, cloud-based natural language processing, response generation through language models, and control of smart home devices through a layered architecture.',
      arch: {
        image: '/General_arch.png',
        caption: 'El sistema está organizado en cuatro capas principales: la capa de usuario contiene las interfaces (asistente de voz e interfaz web), la capa de servicio incluye el orquestador central y servicios modulares, la capa de servicios externos integra síntesis y transformación de texto a voz, base de datos en la nube, inteligencia artificial generativa y servicios IoT, y la capa de hardware agrupa los componentes físicos como pulsador, micrófono, dongle IoT, pantalla y parlante.',
        captionEn: 'The system is organized into four main layers: the user layer contains the interfaces (voice assistant and web interface), the service layer includes the central orchestrator and modular services, the external services layer integrates text-to-speech synthesis, cloud database, generative artificial intelligence, and IoT services, and the hardware layer groups physical components such as the button, microphone, IoT dongle, screen, and speaker.',
      },
      diagram1: {
        image: '/IA_Arq.png',
        caption: 'El flujo comienza con la captura de audio mediante el micrófono conectado a la Raspberry Pi. El audio se envía a Google Cloud Speech-to-Text para transcripción. El texto se procesa mediante un modelo de lenguaje generativo que genera una respuesta contextualizada. Finalmente, la respuesta se convierte a voz mediante síntesis de texto a voz y se reproduce en el parlante.',
        captionEn: 'The flow begins with audio capture through the microphone connected to the Raspberry Pi. Audio is sent to Google Cloud Speech-to-Text for transcription. The text is processed by a generative language model that generates a contextualized response. Finally, the response is converted to speech via text-to-speech synthesis and played through the speaker.',
      },
      diagram2: {
        image: '/iot_arq.png',
        caption: 'La Raspberry Pi actúa como núcleo central conectado al hogar mediante WiFi. Se comunica con Google Cloud Services para obtener datos externos (clima, noticias, información). El sistema también se integra con dispositivos inteligentes del hogar para control remoto mediante comandos de voz, permitiendo automación doméstica desde una interfaz conversacional única.',
        captionEn: 'The Raspberry Pi acts as the central hub connected to the home via WiFi. It communicates with Google Cloud Services to retrieve external data (weather, news, information). The system also integrates with smart home devices for remote control via voice commands, enabling home automation from a single conversational interface.',
      },
      github: 'https://github.com/SteveeAX/Asistente-virtual-',
    },
  },
  {
    title: 'Modelo Predictivo de Potencia en Sistemas Fotovoltaicos',
    titleEn: 'Predictive Power Model for Photovoltaic Systems',
    description: 'Estimación de salida energética en sistemas solares con Machine Learning.',
    descriptionEn: 'Energy output estimation for solar systems using Machine Learning.',
    tags: ['Python', 'Machine Learning', 'Data Analysis'],
    link: null,
    detail: {
      photo: '/SistemaFV.png',
      photoAlt: 'Sistema Fotovoltaico',
      introduction: 'Modelo de machine learning para predicción de potencia de salida en sistemas fotovoltaicos. El proyecto compara cinco arquitecturas: GRU, LSTM, Random Forest, CNN y XGBoost. Utiliza features meteorológicas y temporales como entrada, entrenado en Google Colab con TensorFlow.',
      introductionEn: 'Machine learning model for predicting output power in photovoltaic systems. The project compares five architectures: GRU, LSTM, Random Forest, CNN, and XGBoost. It uses meteorological and temporal features as input, trained on Google Colab with TensorFlow.',
      arch: {
        title: 'Descripción del proyecto',
        titleEn: 'Project Description',
        caption: 'El sistema toma variables meteorológicas (temperatura, humedad, irradiancia, nubosidad) junto con features temporales, las normaliza y las alimenta a cinco modelos en paralelo. GRU y LSTM aprenden patrones temporales con arquitecturas recurrentes, Random Forest captura relaciones no lineales, CNN extrae características espaciales, y XGBoost utiliza gradient boosting para mejorar la precisión.',
        captionEn: 'The system takes meteorological variables (temperature, humidity, irradiance, cloudiness) together with temporal features, normalizes them, and feeds them to five models in parallel. GRU and LSTM learn temporal patterns with recurrent architectures, Random Forest captures non-linear relationships, CNN extracts spatial features, and XGBoost uses gradient boosting to improve accuracy.',
      },
      results: {
        title: 'Resultados comparativos',
        titleEn: 'Comparative Results',
        table: {
          headers: ['Modelo', 'MAE', 'RMSE', 'R²', 'MAPE'],
          rows: [
            ['GRU', '0.047', '0.066', '0.321', '3.01%'],
            ['LSTM', '0.047', '0.066', '0.318', '3.03%'],
            ['Random Forest', '0.048', '0.066', '0.312', '3.06%'],
            ['CNN', '0.048', '0.067', '0.304', '3.10%'],
            ['XGBoost', '0.048', '0.067', '0.291', '3.09%'],
          ],
        },
        conclusion: 'GRU presenta el mejor desempeño con el MAE más bajo (0.047) y el R² más alto (0.321), demostrando que las arquitecturas recurrentes son más efectivas para capturar patrones temporales en datos meteorológicos.',
        conclusionEn: 'GRU achieves the best performance with the lowest MAE (0.047) and highest R² (0.321), demonstrating that recurrent architectures are more effective at capturing temporal patterns in meteorological data.',
      },
      github: 'https://github.com/SteveeAX/Modelo-Predictivo-Fotovoltaico',
    },
  },
  {
    title: 'Monitoreo Eléctrico Residencial',
    titleEn: 'Residential Electrical Monitoring',
    description: 'Sistema IoT con ESP32, AWS IoT Core (MQTT) y frontend Flutter.',
    descriptionEn: 'IoT system with ESP32, AWS IoT Core (MQTT) and Flutter frontend.',
    tags: ['ESP32', 'AWS IoT Core', 'Flutter', 'MQTT'],
    link: null,
  },
];
